/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hicode.swing;

import com.hicode.component.CardItem;
import com.hicode.controller.count;
import com.hicode.controller.LopHocDao;
import javax.swing.ImageIcon;

/**
 *
 * @author HieuHoang
 */
public class FormHome extends javax.swing.JPanel {

    count khd;

    //HocVienDao hvd;
    /**
     * Creates new form FormHome
     */
    public FormHome() {
        initComponents();
        khd = new count();
        card2.setData(new CardItem(new ImageIcon("src\\com\\hicode\\icons\\outline_calendar_today_white_36dp.png"), khd.countsachMuon(), "Sách Mượn"));
        card1.setData(new CardItem(new ImageIcon("src\\com\\hicode\\icons\\outline_class_white_36dp.png"), khd.countDocGia(), "Đọc Giả"));
        card3.setData(new CardItem(new ImageIcon("src\\com\\hicode\\icons\\outline_class_white_36dp.png"), khd.countkhachhang(), "Khách Hàng"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        card2 = new com.hicode.swing.Card();
        card1 = new com.hicode.swing.Card();
        card3 = new com.hicode.swing.Card();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        card2.setColor1(new java.awt.Color(255, 95, 109));
        card2.setColor2(new java.awt.Color(255, 195, 113));
        card2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                card2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLayeredPane1.add(card2);

        card1.setColor1(new java.awt.Color(0, 78, 146));
        card1.setColor2(new java.awt.Color(0, 210, 255));
        jLayeredPane1.add(card1);

        card3.setColor1(new java.awt.Color(196, 224, 229));
        card3.setColor2(new java.awt.Color(76, 161, 175));
        jLayeredPane1.add(card3);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hicode/icons/Thu cmn vien.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void card2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_card2AncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_card2AncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hicode.swing.Card card1;
    private com.hicode.swing.Card card2;
    private com.hicode.swing.Card card3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
